---

# Установка пакетов
- include: install.yml

# Изменим файл настройки авторизации в postgresql
- name: Postgresql | Main | Patch pg_hba
  template:
    src: 'pg_hba.conf'
    dest: '/etc/postgresql/{{ PG_VERSION }}/main/pg_hba.conf'
    owner: 'postgres'
  become: true

# Перезапустим postgresql
- name: Postgresql | Restart service
  systemd:
    name: 'postgresql'
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: true
