---

# Обновим список пакетов
- name: Redis | Install | apt-get update
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 60

# Установим Redis
- name: Redis | Install | install redis-server
  become: true
  apt:
    pkg: '{{ item }}'
    state: present
  with_items:
    - redis-server
