{% if DROP_DATABASE|default(true)|bool == true %}DROP DATABASE IF EXISTS {{ MYSQL_DB }};{% endif %}
CREATE DATABASE IF NOT EXISTS {{ MYSQL_DB }} CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE {{ MYSQL_DB }};
CREATE USER IF NOT EXISTS '{{ MYSQL_USER }}'@'%' IDENTIFIED BY '{{ MYSQL_PASSWORD }}';
GRANT ALL ON {{ MYSQL_DB }} TO '{{ MYSQL_USER }}'@'%';
