---

# Установка пакетов
- include: install.yml

# Перезапустим MySQL
- name: MySQL | Restart service
  systemd:
    name: 'mysql'
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: true
